In [1]:
import numpy as np

### Criando arrays

In [2]:
array = np.array(([1, 2, 3], [4, 5, 6]))
print(array)

array1 = np.array([1, 2, 3])

[[1 2 3]
 [4 5 6]]


In [3]:
for i in array:
    print(i)

[1 2 3]
[4 5 6]


### Initial Placeholders

In [4]:
zeros = np.zeros((3, 4)) #Cria uma matriz 3x4 preenchida com zeros
ones = np.ones((3, 4)) #Cria uma matriz 3x4 preenchida com ums
arange = np.arange(10, 25, 5) #Cria uma matriz de valores espacados, comecando de 10 ate 25 indo de 5 em 5 cada numero
linspace = np.linspace(0, 2, 9) #Cria uma matriz de valores espacados, indo de 0 a 2 com 9 numeros
full = np.full((2, 2), 7) #Cria um array constante 2x2 preenchido com 7
eye = np.eye(2) #Cria uma matriz identidade 2x2
empty = np.empty((3, 2)) #Cria uma matriz 3x2 vazia

In [5]:
print(zeros)
print()
print(ones)
print()
print(arange)
print()
print(linspace)
print()
print(full)
print()
print(eye)
print()
print(empty)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[10 15 20]

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

[[7 7]
 [7 7]]

[[1. 0.]
 [0. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Inspecting Your Array

In [6]:
ones.shape #Verifica a dimensao do array

(3, 4)

In [7]:
array = np.array([1, 2, 3, 4, 5])

In [8]:
len(array) #Verifica o tamanho do array

5

In [9]:
array.ndim #Numeros de dimensoes do vetor

1

In [10]:
array.size #Numeros de elementos do array

5

In [11]:
array.dtype #Tipo do array

dtype('int32')

In [12]:
array.dtype.name #Nome do tipo do array


'int32'

In [13]:
array.astype(int) #Converte o vetor para diferente tipos

array([1, 2, 3, 4, 5])

### Arithmetic Operations

In [17]:
a = np.array([1, 2, 3, 4, 10])
b = np.array([1, 2, 3, 4, 5])

In [33]:
print(a - b)
print(a + b)
print(a / b)
print(a * b)
print(np.exp(a)) #Exponencial do vetor a
print(np.sqrt(a)) #Raiz quadrada do vetor a
print(np.sin(a)) #Seno do vetor a
print(np.cos(a)) #Cosseno do vetor a
print(np.log(a)) #Logaritmo do vetor a
print(np.dot(a, b)) #Produto interno de a por b

[0 0 0 0 5]
[ 2  4  6  8 15]
[1. 1. 1. 1. 2.]
[ 1  4  9 16 50]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 2.20264658e+04]
[1.         1.41421356 1.73205081 2.         3.16227766]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362 -0.83907153]
[0.         0.69314718 1.09861229 1.38629436 2.30258509]
80


### Comparison

In [35]:
a == b #Comparando os elementos de a com b

array([ True,  True,  True,  True, False])

In [36]:
a < 2 #Verificando se os elementos de a sao menores que 2

array([ True, False, False, False, False])

 ### Aggregate Functions

In [55]:
print(a.sum()) #Soma dos elementos de a
print(a.min()) #Maior elemento de a
print(b.max(axis=0)) #Menor elemento de b, axis = 0, verifica a linha
print(b.cumsum()) #Soma de uma sequência de números que é atualizada cada vez que um novo número é adicionado à sequência
print(a.mean()) #Media do vetor a
print(np.median(b)) #Mediana do vetor b
print(np.corrcoef(a, b)) #Coeficiente de correlacao de a com b

20
1
5
[ 1  3  6 10 15]
4.0
3.0
[[1.         0.89442719]
 [0.89442719 1.        ]]


### Copying Arrays

In [63]:
h = a.view() #Crindo uma visão da matriz com os mesmos dados
print(h)
c = np.copy(a) #Criando uma copia do vetor
print(c)
h = a.copy() #Criando uma cópia profunda da matriz
print(h)

[ 1  2  3  4 10]
[ 1  2  3  4 10]
[ 1  2  3  4 10]


### Sorting Arrays

In [84]:
a.sort() # Classificar uma matriz
c.sort(axis=0) #Classifica os elementos do eixo de uma matriz

### Subsetting, Slicing, Indexing

#### Subsetting

In [98]:
matriz = np.array(([1, 3, 5], [2, 4, 6]))
matriz

array([[1, 3, 5],
       [2, 4, 6]])

In [99]:
print(a) #Vetor
print(a[2]) #Indice 2
print(matriz[1, 2]) #Pega o elemento 6, da linha 1 e coluna 2

[ 1  2  3  4 10]
3
6


#### Slicing

In [105]:
print(a[0:2]) #Seleciona todos os elementos do indice 0 ao indice 2
print(matriz[0:3,1]) #Selecione os itens nas linhas 0 e 1 na coluna 1

[1 2]
[3 4]


In [106]:
matriz[:1] #Selecione todos os itens na linha 0 (equivalente a b[0:1,:])

array([[1, 3, 5]])

In [108]:
matriz[1, ...] #O mesmo que [1,:,:], todos os elementos da linha 1

array([2, 4, 6])

In [109]:
a[ : :-1] #Reverter o vetor

array([10,  4,  3,  2,  1])

#### Boolean Indexing

In [114]:
a[a < 2] #Selecione elementos de menos de 2

array([1])

#### Fancy Indexing

In [115]:
matriz[[1, 0, 1, 0], [0, 1, 2, 0]] #Selencionando os elementos (1, 0),(0, 1), (1, 2), (0, 0)

array([2, 3, 6, 1])

In [117]:
 matriz[[1, 0, 1, 0]][:,[0,1,2,0]] #Selecione um subconjunto das linhas da matriz e colunas

array([[2, 4, 6, 2],
       [1, 3, 5, 1],
       [2, 4, 6, 2],
       [1, 3, 5, 1]])

### Array Manipulation

####  Transposing Array

In [120]:
i = np.transpose(matriz) #Matriz transposta
i

array([[1, 2],
       [3, 4],
       [5, 6]])